version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --prod
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/help/ s3://sanj44-helpccc-app-2022 --delete